config/routes.rb
Depot::Application.routes.draw do
  

  get "admin" => "admin#index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end
  

  resources :users

  resources :orders

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end
  resources :line_items
  resources :carts

  root :to => 'store#index', :as => "store"

  match "line_items/decrement", :to=> 'line_items#decrement', :method=>:post
  match "line_items/increment", :to=> 'line_items#increment', :method=>:post

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= stylesheet_link_tag "depot" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body id="store">
    <div id="banner">
      <%= image_tag("/images/logo.png") %>
      <%= @page_title || "prag book" %>

    </div>
    <div id="columns">
      <div id="side">
        <% if @cart %>
          <div id="cart"

                 <% if @cart.total_items == 0 %>
                   style="display: none"
                 <% end %>

               >

            <%= render(@cart) %>
          </div>
        <% end %>
        <a href="/">Home</a><br/>
        <a href="/faq">Questions</a><br/>
        <a href="/news">News</a><br/>
        <a href="/contact">Contact</a><br/>

        <% if session[:user_id] %>
          <br/>
            <%= link_to 'Orders', orders_path %><br/>
            <%= link_to 'Products', products_path %><br/>
            <%= link_to 'Users', users_path %><br/>
          <br/>
          <%= button_to 'Logout', logout_path, :method => :delete %>
        <% end %>

      </div>

      <div id="main">
        <%= yield %>
      </div>

    </div>
  </body>
</html>